################################################################################
# CUPLA_CXX                             : {g++, clang++}
#   [g++]                               : {5, 6, 7, 8, 9} <list>
#   [clang++]                           : {4.0, 5.0, 6.0, 7, 8, 9, 10} <list>
# CUPLA_BOOST_VERSIONS                  : {1.65.1, 1.66.0, 1.67.0, 1.68.0, 1.69.0, 1.70.0, 1.71.0, 1.72.0, 1.73.0} <list>
# CUPLA_BUILD_TYPE                      : {Debug, Release}
# CUPLA_CMAKE_ARGS                      : <string>
include:
  - local: '/script/compiler_base.yml'

cuda92:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda9.2
  variables:
    CUPLA_BOOST_VERSIONS: "1.65.1 1.70.0 1.73.0"
  extends: .base_cuda

cuda100:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.0
  variables:
    CUPLA_BOOST_VERSIONS: 1.73.0
  extends: .base_cuda

cuda101:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.1
  variables:
    CUPLA_BOOST_VERSIONS: 1.73.0
  extends: .base_cuda

cuda102:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.2
  variables:
    CUPLA_BOOST_VERSIONS: 1.73.0
  extends: .base_cuda

gcc7:
  variables:
    CUPLA_CXX: "g++-5 g++-7 g++-9"
    CUPLA_BOOST_VERSIONS: "1.65.1 1.70.0 1.73.0"
  extends: .base_gcc

clang7:
  variables:
    CUPLA_CXX: "clang++-5.0 clang++-7 clang++-9"
    CUPLA_BOOST_VERSIONS: "1.65.1 1.70.0 1.73.0"
  extends: .base_clang
