include:
  - local: '/script/compiler_base.yml'

cuda92:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda9.2
  variables:
    BOOST_VERSION: 1.73.0
  extends: .base_cuda

cuda100:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.0
  variables:
    BOOST_VERSION: 1.73.0
  extends: .base_cuda

cuda101:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.1
  variables:
    BOOST_VERSION: 1.73.0
  extends: .base_cuda

cuda102:
  image: registry.gitlab.com/hzdr/crp/alpaka-group-container/alpaka-ci:cuda10.2
  variables:
    BOOST_VERSION: 1.73.0
  extends: .base_cuda

gcc7:
  variables:
    CXX: g++
    CC: gcc
    BOOST_VERSION: 1.73.0
  extends: .base_gcc

clang7:
  variables:
    CXX: clang++-7
    CC: clang-7
    BOOST_VERSION: 1.73.0
  extends: .base_clang
